Feature/image-rest-api | Homework # 1
JudexMars/ImageProcessingAPI pull request #1
Opened 2024-04-05 11:54 UTC by JudexMars

# Homework # 1
- API
- Покрытие кода
- Примеры запросов

## API
Реализовал требуемый API. В директории `src/main/resources` представлена оригинальная спецификация – `openapi-example.yaml`, а также актуальная – `api.yaml`.

Провел сравнение спецификаций с помощью openapi-diff и oasdiff (openapi-diff срабатывает во время validate).

Фактические отличия: дополнительный эндпоинт для аутентификации и security requirement на эндпоинтах image (т.к. пользователь видит только свои картинки).

### Openapi-diff:
<img width="654" alt="Screenshot 2024-04-05 at 14 32 25" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/a3a11775-fb12-43f9-8bae-bfaf33050605">

### Oasdiff:
```
### New Endpoints: 3
--------------------
POST /auth/login  
POST /auth/refresh  
POST /auth/signup  

### Deleted Endpoints: None
---------------------------

### Modified Endpoints: 4
-------------------------
POST /image
- Description changed from 'В рамках данного метода необходимо:
1. Провалидировать файл. Максимальный размер файла - 10Мб, поддерживаемые расширения - png, jpeg.
1. Загрузить файл в S3 хранилище.
1. Сохранить в БД мета-данные файла - название; размер; ИД файла в S3; ИД пользователя, которому файл принадлежит.
' to 'В рамках данного метода необходимо:
1. Провалидировать файл. Максимальный размер файла - 10Мб, поддерживаемые расширения - png, jpeg.
2. Загрузить файл в S3 хранилище.
3. Сохранить в БД мета-данные файла - название; размер; ИД файла в S3; ИД пользователя, которому файл принадлежит.'
- Security changed
  - New security requirements: Auth

DELETE /image/{image-id}
- Description changed from 'В рамках данного метода необходимо:
1. Проверить, есть ли такой файл в системе.
1. Проверить, доступен ли данный файл пользователю.
1. Удалить файл.
' to 'В рамках данного метода необходимо:
1. Проверить, есть ли такой файл в системе.
2. Проверить, доступен ли данный файл пользователю.
3. Удалить файл.'
- Security changed
  - New security requirements: Auth

GET /image/{image-id}
- Description changed from 'В рамках данного метода необходимо:
1. Проверить, есть ли такой файл в системе.
1. Проверить, доступен ли данный файл пользователю.
1. Скачать файл.
' to 'В рамках данного метода необходимо:
1. Проверить, есть ли такой файл в системе.
2. Проверить, доступен ли данный файл пользователю.
3. Скачать файл.'
- Security changed
  - New security requirements: Auth

GET /images
- Description changed from 'В рамках данного метода необходимо:
1. Получить мета-информацию о всех изображениях, которые доступны пользователю
' to 'В рамках данного метода необходимо:
1. Получить мета-информацию о всех изображениях, которые доступны пользователю'
- Security changed
  - New security requirements: Auth
```

### Swagger:

<img width="1459" alt="Screenshot 2024-04-05 at 14 44 07" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/2f9e9e28-0c8a-413c-a923-c110ec2a5542">

## Покрытие кода

<img width="1156" alt="Screenshot 2024-04-05 at 14 43 11" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/5f63b590-711d-4070-9aa8-be8d451b9018">

## Примеры запросов

### Регистрация:
<img width="1406" alt="Screenshot 2024-04-05 at 13 02 47" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/788715da-8d79-426c-b709-f85cfed75fa0">

### Загрузка (upload) картинки:
<img width="491" alt="Screenshot 2024-04-05 at 13 51 01" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/719f28f3-c941-454f-adf5-4841ac7be9a2">
<img width="683" alt="Screenshot 2024-04-05 at 13 52 38" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/eb70f8f2-c9c0-4548-88f8-37402505c481">

### Просмотр списка доступных картинок:
<img width="519" alt="Screenshot 2024-04-05 at 13 51 16" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/725afb08-6c3f-41ac-a249-45a5e3351a46">

### Скачивание картинки:
<img width="571" alt="Screenshot 2024-04-05 at 13 51 26" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/e8d362df-5258-44e6-9c23-5d22916340f1">
<img width="703" alt="Screenshot 2024-04-05 at 13 38 01" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/7fb692ac-aae3-4eb2-a8aa-fe2f58c47610">

### Удаление картинки:
<img width="550" alt="Screenshot 2024-04-05 at 13 51 38" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/91de3e0b-9fbb-4030-b982-204e6c8cc9f6">
<img width="544" alt="Screenshot 2024-04-05 at 13 52 44" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/cfaa8edf-c67f-45d0-9f0a-863d1555fbbe">

2024-05-11 16:12 UTC, MaximKozlyuk requested changes

2024-05-11 16:12 UTC, MaximKozlyuk commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/ImageController.java
> +        var meta = imageService.getImageMeta(id);
fyi: `getImageMeta` 2 раза дергается база. Думаю можно в `downloadImage` прокидывать `ImageDto` или как-то иначе поступить.

2024-05-11 16:12 UTC, MaximKozlyuk commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/ImageController.java
> +            2. Проверить, доступен ли данный файл пользователю.
Я мб не нашел, но как реализован пункт требований для этого метода? Кажется не сделано.
`необходимо сделать так, чтобы картинку мог просматривать только тот пользователь, который ее загрузил`

2024-05-11 16:12 UTC, MaximKozlyuk commented on image-crud/src/test/java/org/judexmars/imagecrud/unit/service/S3ServiceTest.kt
> +internal class S3ServiceTest {
за тесты на котлине лайк, хоть и сам его не знаю :peka:

2024-05-11 16:21 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/ImageController.java
> +            2. Проверить, доступен ли данный файл пользователю.
Да, точно. Пропустил этот момент

2024-05-12 12:08 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/ImageController.java
> +        var meta = imageService.getImageMeta(id);
Я решил перенести вызов .getImageMeta внутрь метода downloadImage в сервисе и возвращать DTO со всеми нужными данными. Думаю, так попроще будет

2024-05-12 12:13 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/ImageController.java
> +            2. Проверить, доступен ли данный файл пользователю.
Сейчас чекнул, оказывается, в следующих домашках был код с этой проверкой почему-то. В общем, я сейчас добавил передачу id текущего аккаунта в .downloadImage, чтобы внутри сервиса сверять его с id автора картинки.

2024-05-12 12:16 UTC, JudexMars commented on image-crud/src/test/java/org/judexmars/imagecrud/unit/service/S3ServiceTest.kt
> +internal class S3ServiceTest {
Ну вообще ощущается, как будто пишешь на джаве со встроенным ломбоком, если сильно не погружаться в фичи)

2024-05-13 13:55 UTC, SHvatov commented on image-crud/src/test/java/org/judexmars/imagecrud/unit/service/S3ServiceTest.kt
> +internal class S3ServiceTest {
я все вижу...

![image](https://github.com/JudexMars/ImageProcessingAPI/assets/15994914/e0e0ab15-109d-4c7a-b668-ff0749a016d7)

2024-05-13 14:13 UTC, SHvatov requested changes
@JudexMars оставил пару комментариев, посмотри плиз

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/config/DataLoader.java
> +//    @Bean
Вот такое стоит сразу в топку, ибо профита ноль, а место занимает)

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/config/DataLoader.java
> +public class DataLoader implements ApplicationRunner {
https://habr.com/ru/articles/572828/

Я бы через систему ивентов советовал бы инициализировать данные. Или вообще через ликвибейз / flyway

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/AuthController.java
> +        return new JwtResponseDto(
Интересная последовательность токенов) И почему бы не формировать JwtResponseDto в authService? Или что-то более хьюман-френдли?)

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/AuthController.java
> +        var tokens = authService.createAuthTokens(account, name, password);
Как-то создание ответа и параллельное создание токенов у меня немного не сходятся. И хорошо бы, чтобы createAuthTokens тоже возвращал что-то более осознанное)

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/ImageController.java
> +        var username = securityUtils.getLoggedInUsername();
1. securityUtils - утильный класс, однако в твоем случае это компонент, что как-то немного не вяжется, ибо утильные классы зачастую предоставляют набор статических вспомогательных методов. 
2. Через `@AuthenticationPrincipal` пользователя не получить?
3. Данная связка - получение username, а по нему аккаунта встречается несколько раз, стоит унести в метод.

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/exception/NoSuchRoleException.java
> +
Многовато пустых строк)

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/exception/handler/AppExceptionHandler.java
> +    protected ResponseEntity<BaseResponseDto> handleMethodArgumentNotValid(MethodArgumentNotValidException ex) {
Можно просто handle, и почему методы protceted?

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/repository/AccountRepository.java
> +
Много пустых строк

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/security/JwtRequestFilter.java
> +    ) throws ServletException, IOException {
`@SneakyThrows`

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/security/JwtRequestFilter.java
> +        String username = null;
Мне не очень нравится, когда объявление и определение переменной происходят ни в один и тот же момент времени. Почему бы получение username не вынести в отдельный метод `getUsernameFromToken`?

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/security/JwtRequestFilter.java
> +    private final JwtTokenUtils jwtTokenUtils;
Снова утильный класс превращен в бин. Давай переименуем как-нибудь, а то непривычна такая связка названия и назначения.

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/security/JwtRequestFilter.java
> +            SecurityContextHolder.getContext().setAuthentication(token);
Ой, вот это как-то не идеоматично. Почему бы не использовать стандартные средства спринга для генерации авторизационного объекта?

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/security/JwtRequestFilter.java
> +            SecurityContextHolder.getContext().setAuthentication(token);
https://habr.com/ru/articles/784508/

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/security/JwtRequestFilter.java
> +            SecurityContextHolder.getContext().setAuthentication(token);
Просто этот контекст утильный, и его бы, по-хорошему, сам спринг должен заполнять.

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/S3Service.java
> +    public void init() throws Exception {
Тогда throws не нужен)

2024-05-13 14:13 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/S3Service.java
> +        if (!client.bucketExists(BucketExistsArgs.builder().bucket(properties.getBucket()).build())) {
А если в параллель будут бакеты создаваться, тут все ок будет?

2024-05-13 15:14 UTC, merged

2024-05-13 20:04 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/service/S3Service.java
> +        if (!client.bucketExists(BucketExistsArgs.builder().bucket(properties.getBucket()).build())) {
В какой-то момент опытным путем было выяснено, что нет, поэтому было принято решение создавать бакеты только в этом модуле

2024-05-13 20:05 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/service/S3Service.java
> +    public void init() throws Exception {
Похоже Idea подставила, но да в общем

2024-05-13 20:11 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/ImageController.java
> +        var username = securityUtils.getLoggedInUsername();
1. securityUtils действительно можно как статик использовать, тут просчитался
2. Помню пытался эту аннотацию использовать в прошлом, но какая-то проблема была с ней. Возможно связанная как раз с тем, как я с security контекстом работаю. Изучу вопрос еще раз
3. Согласен

2024-05-13 20:42 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/security/JwtRequestFilter.java
> +    private final JwtTokenUtils jwtTokenUtils;
По логике это Service должен быть?

2024-05-13 20:51 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/config/DataLoader.java
> +public class DataLoader implements ApplicationRunner {
> Если нам не нужны аргументы командной строки, это лучший способ выполнить код после запуска приложения.

А есть заметная разница EventListener с ApplicationRunner на практике?

2024-05-13 20:58 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/exception/handler/AppExceptionHandler.java
> +    protected ResponseEntity<BaseResponseDto> handleMethodArgumentNotValid(MethodArgumentNotValidException ex) {
Изначально наследовался от другого резолвера и там метод был с модификатором protected...

2024-05-13 21:05 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/AuthController.java
> +        return new JwtResponseDto(
Ну... Да, согласен. Можно было ДТО тут заюзать. Почему-то в тот момент не хотел плодить классы

2024-05-13 21:07 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/config/DataLoader.java
> +//    @Bean
Не замёл следы преступления...

2024-05-14 20:31 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/config/DataLoader.java
> +public class DataLoader implements ApplicationRunner {
На практике я ни разу не видел использования раннеров) Да и ивенты более детерминированные в плане того, когда они запускаются.

2024-05-14 20:31 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/AuthController.java
> +        return new JwtResponseDto(
Большая часть нашей работы - плодить классы) Мы же ООПшники)

2024-05-14 20:32 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/ImageController.java
> +        var username = securityUtils.getLoggedInUsername();
2 скорее всего из-за того, что немного нетривиальный способ заполнения контекста в обход менеджера авторизации.

2024-05-14 20:33 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/security/JwtRequestFilter.java
> +    private final JwtTokenUtils jwtTokenUtils;
Ага)

2024-05-14 20:33 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/S3Service.java
> +        if (!client.bucketExists(BucketExistsArgs.builder().bucket(properties.getBucket()).build())) {
Оки доки, но тогда возникают проблемсы когда несколько реплик)