Feature/kafka
JudexMars/ImageProcessingAPI pull request #5
Opened 2024-04-21 16:48 UTC by JudexMars

# Homework # 3
- API
- Kafka
- Демонстрация работы

## API
Реализовал требуемый API. В директории `src/main/resources` представлена оригинальная спецификация – `openapi-example.yaml`, а также актуальная – `api.yaml`.

Провел сравнение спецификаций с помощью openapi-diff и oasdiff (openapi-diff срабатывает во время validate).

### Openapi-diff:
<img width="652" alt="Screenshot 2024-04-21 at 19 20 03" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/a0a6676e-9c6c-4e20-8609-9d0681b5a52c">

### Oasdiff:

```
### New Endpoints: 3
--------------------
POST /auth/login  
POST /auth/refresh  
POST /auth/signup  

### Deleted Endpoints: None
---------------------------

### Modified Endpoints: 6
-------------------------
POST /image
- Description changed from 'В рамках данного метода необходимо:
1. Провалидировать файл. Максимальный размер файла - 10Мб, поддерживаемые расширения - png, jpeg.
1. Загрузить файл в S3 хранилище.
1. Сохранить в БД мета-данные файла - название; размер; ИД файла в S3; ИД пользователя, которому файл принадлежит.
' to 'В рамках данного метода необходимо:
1. Провалидировать файл. Максимальный размер файла - 10Мб, 
поддерживаемые расширения - png, jpeg.
2. Загрузить файл в S3 хранилище.
3. Сохранить в БД мета-данные файла - название; размер; ИД файла в S3; ИД пользователя, 
которому файл принадлежит.'
- Security changed
  - New security requirements: Auth

DELETE /image/{image-id}
- Description changed from 'В рамках данного метода необходимо:
1. Проверить, есть ли такой файл в системе.
1. Проверить, доступен ли данный файл пользователю.
1. Удалить файл.
' to 'В рамках данного метода необходимо:
1. Проверить, есть ли такой файл в системе.
2. Проверить, доступен ли данный файл пользователю.
3. Удалить файл.'
- Security changed
  - New security requirements: Auth

GET /image/{image-id}
- Description changed from 'В рамках данного метода необходимо:
1. Проверить, есть ли такой файл в системе.
1. Проверить, доступен ли данный файл пользователю.
1. Скачать файл.
' to 'В рамках данного метода необходимо:
1. Проверить, есть ли такой файл в системе.
2. Проверить, доступен ли данный файл пользователю.
3. Скачать файл.'
- Security changed
  - New security requirements: Auth

POST /image/{image-id}/filters/apply
- Description changed from 'В рамках данного метода необходимо:
1. Проверить, есть ли у пользователя доступ к файлу
1. Сохранить в БД новый запрос на изменение файла:
    1. статус = WIP
    2. ИД оригинальной картинки = ИД оригинального файла
    3. ИД измененной картинки = null
    4. ИД запроса = уникальный ИД запроса в системе
1. Отправить в Kafka событие о создании запроса
1. Убедиться, что шаг 3 выполнен успешно, в противном случае выполнить повторную попытку
1. Вернуть пользователю ИД его запроса
' to 'В рамках данного метода необходимо:
1. Проверить, есть ли у пользователя доступ к файлу
2. Сохранить в БД новый запрос на изменение файла:
    1. статус = WIP
    2. ИД оригинальной картинки = ИД оригинального файла
    3. ИД измененной картинки = null
    4. ИД запроса = уникальный ИД запроса в системе
3. Отправить в Kafka событие о создании запроса
4. Убедиться, что шаг 3 выполнен успешно, в противном случае выполнить повторную попытку
5. Вернуть пользователю ИД его запроса'
- Security changed
  - New security requirements: Auth

GET /image/{image-id}/filters/{request-id}
- Security changed
  - New security requirements: Auth

GET /images
- Description changed from 'В рамках данного метода необходимо:
1. Получить мета-информацию о всех изображениях, которые доступны пользователю
' to 'В рамках данного метода необходимо:
1. Получить мета-информацию о всех изображениях, которые доступны пользователю'
- Security changed
  - New security requirements: Auth
```

## Kafka

Настроил Kafka в режиме Kraft, так как с Zookeeper мы уже работали на семинаре и мне хотелось попробовать что-нибудь новенькое. У этого есть, как минимум, 1 плюс - на один контейнер меньше поднимать! Как и требовалось, для безопасности настроил аутентификацию через SASL по SSL. Все связанные с этим файлы находятся в `/image-crud/environment/kafka/`. Помимо прочего, поднял в отдельном контейнере Kafka UI для тестирования брокеров, так как по заданию обработчиков картинок у нас еще нет.

## Демонстрация работы

1. Загрузим тестовую картинку

<img width="547" alt="Screenshot 2024-04-21 at 19 31 30" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/e7937d08-cab1-431c-9317-79aa9731ac54">

2. Применим к ней фильтры

<img width="751" alt="Screenshot 2024-04-21 at 19 33 53" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/5e8d0fc8-9e01-4d78-ae5b-165662e4af96">

<img width="951" alt="Screenshot 2024-04-21 at 19 34 30" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/cd43b420-c994-428c-bf1c-bfc04886b8d0">

В бд появилась запись о поступившем запросе:

<img width="745" alt="Screenshot 2024-04-21 at 19 35 04" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/00555353-dcb7-4926-a0bc-f9bb4516138c">

Можем наблюдать, что в соответствующем топике появилось сообщение о применении фильтров к картинке

<img width="1310" alt="Screenshot 2024-04-21 at 19 38 18" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/54d68ba5-216c-4a01-9d8c-95a40e151149">

3. Представим, что все обработчики выполнили свою работу и картинка готова. Отправим сообщение об этом в топик `images.done`.

<img width="1308" alt="Screenshot 2024-04-21 at 19 43 36" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/16ad6a14-46de-41e3-9fec-9db5962c4d04">

<img width="1280" alt="Screenshot 2024-04-21 at 19 44 27" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/06ba47ed-2ac6-472b-b7ac-c33c4f7b4836">

4. Теперь сделаем запрос для получения модифицированной картинки.

<img width="887" alt="Screenshot 2024-04-21 at 19 46 04" src="https://github.com/JudexMars/ImageProcessingAPI/assets/36617982/7ae1ba05-f61a-4ed7-8017-98c130c04fc4">

Как видно, информация в БД обновилась и всё хорошо

2024-05-14 20:51 UTC, SHvatov requested changes
@JudexMars оставил пару комментариев, погляди плиз)
А так 🔥 🚀

2024-05-14 20:51 UTC, SHvatov commented on image-crud/pom.xml
> +                <version>3.6.3</version>
На будущее просто совет - версии выносить в проперти, так гораздо проще их менеджить)

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/config/DataLoader.java
>      initPrivileges();
1. Все еще раннер)
2. Он становится ультимативной точкой по инициализации всего и вся, что не есть хорошо. И нельзя ли это все унести в ликви скрипты?

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/config/kafka/KafkaInitializer.java
> + * Kafka configuration.
😄 Можно просто класс назвать `KafkaConfiguration`))

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/controller/ImageFiltersController.java
> +    var loggedInUsername = securityUtils.getLoggedInUsername();
Напоминалка про связку `getLoggedInUsername -> getByUsername`

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/dto/imagefilters/ApplyImageFiltersResponseDto.java
> +public record ApplyImageFiltersResponseDto(
ApplyImageFiltersResponseDto -> ApplyImageFiltersResponse. ИМХО, указание, что это DTO, в названии класса стоит делать, только когда данное название уже забито за другой сущностью.

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/model/ApplyFilterRequestEntity.java
> +  @ManyToOne
Честно говоря, меня немного смущают такие `ManyToOne` без `JoinColumn`

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/model/ApplyFilterRequestEntity.java
> +  @ManyToOne
И еще небольшое наблюдение из опыта
1. Я бы добавил FetchType.LAZY - ведт не всегда все эти данные тебе нужны, а запросы бегут
2. Вообще есть тенденция отказа от `...To...` в пользу указания просто ИД. И запрашивают в таком случае данные только когда надо. Во-первых - перфоманс, во-вторых - у гибера есть много кеков с джойнами)

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/ImageFiltersService.java
> +    var meta = imageService.getImageMetaAsEntitySafely(imageId, accountId);
Вот тут, наверное, не хватает транзакции - в топик не отправили, а в БД уже сохранили.

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/ImageFiltersService.java
> +  @KafkaListener(
Оу ноу, тут же нарушение Single Responsibility Principle! Заявление оформлено и отправлено дядюшке Бобу, у вас есть неделя на исправление)

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/ImageFiltersService.java
> +  public void consumeDoneImage(ConsumerRecord<String, ImageStatusMessage> record,
> В консьюмерах попробуйте реализовать вот такие ретраи - https://www.baeldung.com/spring-retry-kafka-consumer. В продьюсерах ретраи есть из коробки, нужно просто сконфигурить - https://stackoverflow.com/questions/68765978/how-to-implement-retries-on-spring-kafka-producer.

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/ImageFiltersService.java
> +    var value = record.value();
лисенеры из коробки поддерживают маппинг в дто

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/ImageService.java
> +  public void deleteImage(UUID id, UUID accountId) throws DeleteFileException {
ой, а зачем тут ето? никто не любит чекед эксепшенс

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/ImageService.java
> +  ImageEntity getImageMetaAsEntity(UUID id) {
а тут почему package-private?

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/KafkaConsumer.java
> +public class KafkaConsumer {
Стоит конкретизировать название

2024-05-14 20:51 UTC, SHvatov commented on image-crud/src/test/java/org/judexmars/imagecrud/unit/service/ImageFiltersServiceTest.kt
> +internal class ImageFiltersServiceTest {
Тестов маловато, код на котлине я почелленджу уже завтра) Только ты мне напомни, елси я вдруг забуду)

2024-05-15 09:42 UTC, JudexMars commented on image-crud/src/main/java/org/judexmars/imagecrud/service/ImageService.java
> +  ImageEntity getImageMetaAsEntity(UUID id) {
В этой ветке этот метод используется только в другом сервисе (ImageFiltersService). Я посчитал, что тогда public писать излишне.

2024-05-15 09:57 UTC, SHvatov commented on image-crud/src/main/java/org/judexmars/imagecrud/service/ImageService.java
> +  ImageEntity getImageMetaAsEntity(UUID id) {
Давай public)

2024-05-15 17:47 UTC, JudexMars commented on image-crud/src/test/java/org/judexmars/imagecrud/unit/service/ImageFiltersServiceTest.kt
> +internal class ImageFiltersServiceTest {
Хорошо

2024-05-31 23:25 UTC, merged