test pr 09.05
JudexMars/ImageProcessingAPI pull request #6
Opened 2024-05-09 20:36 UTC by JudexMars

2024-05-14 21:04 UTC, SHvatov requested changes
@JudexMars и снова 🔥, оставил пару комментов, погляди плиз.

2024-05-14 21:04 UTC, SHvatov commented on cv-image-processor/app.py
> +from kafka import KafkaProducer, KafkaConsumer
о-ля-ля, пит~~ух~~он!

2024-05-14 21:04 UTC, SHvatov commented on cv-image-processor/app.py
> +REDIS_HOST = os.getenv('REDIS_HOST', 'remove-background-processor-redis')
И редиска еще, ну вообще жесть)

2024-05-14 21:04 UTC, SHvatov commented on cv-image-processor/app.py
> +from kafka import KafkaProducer, KafkaConsumer
Сделаем вид, что я посмотрел и все ок)

2024-05-14 21:04 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/dto/ImageDto.kt
> +@JvmRecord
Вот это немного избыточно, ибо я не вижу интеграции котлина и жабы)

2024-05-14 21:04 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/dto/ImageDto.kt
> +    override fun equals(other: Any?): Boolean {
А того иквалса, что из коробки для дата-классов недостаточно?

2024-05-14 21:04 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/BrightnessProcessor.kt
> +    fun adjustBrightness(
private наверное?

2024-05-14 21:04 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/BrightnessProcessor.kt
> +                "image/jpeg" -> JpegWriter.CompressionFromMetaData
В `MimeTypeUtils` уже есть константы

2024-05-14 21:04 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/CropProcessor.kt
> +        val x1 = props["x1"]
Можно через ObjectMapper в DTO красивенько конвертнуть, и не париться)

2024-05-14 21:04 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/CropProcessor.kt
> +        var nextImageId = message.imageId
И вот эта логика повторяется. Можно вынести в абстрактный класс, который:
1. Чекает, есть ли необработанные фильтры и равен ли первый типу текущего
2. Маппит проперти в нужную ДТО
3. Вызывает абстрактный метод реализацию фильтра
4. Формирует ответное сообщение на основе результатов работы

2024-05-14 21:04 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/CropProcessor.kt
> +        var nextImageId = message.imageId
И еще стоит эти параметры валидировать

2024-05-14 21:04 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/CropProcessor.kt
> +            val source: S3ImageDto =
вот это тоже дублируется, надобно вынести

2024-05-14 21:04 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/ProcessorListener.kt
> +        val imageId = redisTemplate.opsForValue().get(record.value().requestId.toString())
1. Нет валидаций, а никому верить и доверять нельзя
2. `record.value().requestId.toString()` встречается много раз, стоит сделать один раз и в переменную запихнуть, будет покрасивее

2024-05-15 09:55 UTC, JudexMars commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/dto/ImageDto.kt
> +    override fun equals(other: Any?): Boolean {
Мне идея (2024.1.1) подсказала, что надо переопределять equals, если одна из проперти – это массив, потому что data class сам для них не пишет .contentEquals()

2024-05-15 09:58 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/dto/ImageDto.kt
> +    override fun equals(other: Any?): Boolean {
Понял принял, спасибо идее, будем знать!

2024-05-15 10:00 UTC, JudexMars commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/BrightnessProcessor.kt
> +    fun adjustBrightness(
Да, точно

2024-05-15 10:01 UTC, JudexMars commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/CropProcessor.kt
> +        var nextImageId = message.imageId
Хорошо, попробую так сделать

2024-05-17 18:40 UTC, JudexMars commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/ProcessorListener.kt
> +        val imageId = redisTemplate.opsForValue().get(record.value().requestId.toString())
Я не очень понял, что ты имеешь ввиду тут под валидациями. Ты про ситуацию, когда есть несуществующие фильтры? Или что-то еще?

2024-05-17 19:22 UTC, JudexMars commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/ProcessorListener.kt
> +        val imageId = redisTemplate.opsForValue().get(record.value().requestId.toString())
Или ты про исключение во время маппинга на ДТО?

2024-05-30 15:56 UTC, SHvatov commented on image-processor/src/main/kotlin/org/judexmars/imageprocessor/service/ProcessorListener.kt
> +        val imageId = redisTemplate.opsForValue().get(record.value().requestId.toString())
Да, все верно - с точки зрения того, что в консьюмер в принципе была передана некорректного рода сущность и он ушел в луп ошибок десериализации. Я вроде бы кидал статью на баелдунге про то, как стоит такое хэндлить.

2024-06-12 07:48 UTC, SHvatov commented
@JudexMars 🔥, можно мержить)

2024-06-12 09:41 UTC, merged